spring:
  application:
    name: config
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dongkki/msa_spring.git
          username: dongkki
          password: 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
          searchPaths: /prop, /prop/{application}
          clone-on-start: true

server:
  port: 8070