spring:
  application:
    name: config
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dongkki/msa.git
          username: dongkki
          password: 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
          searchPaths: /prop, /prop/{application}
          clone-on-start: true

server:
  port: 8070